version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 # Asegúrate de que esta versión sea compatible con tu proyecto
    commands:
      - echo "Installing dependencies..."
      - pip install robotframework
      - pip install robotframework-requests
      - pip install robotframework-operating-system
      - pip install requests

  pre_build:
    commands:
      - echo "Setting up environment..."
      # Configura variables necesarias si aplica (puedes usar SSM o secretos)
      - python3 --version
      - pip3 --version
      - robot --version
      - export BASE_URL=https://jsonplaceholder.typicode.com
     

  build:
    commands:
      - echo "Running Robot Framework tests..."
      - robot mentorShip.robot

  post_build:
    commands:
      - echo "Archiving test results..."
      - mkdir -p artifacts
      - cp output/* artifacts/  # Copia los resultados generados por Robot Framework para almacenarlos como artefactos

artifacts:
  files:
    - artifacts/**  # Sube los resultados al bucket S3 configurado para tu pipeline
  discard-paths: no

