version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install robotframework
      - pip install robotframework-requests
      - pip install requests

  pre_build:
    commands:
      - echo "Setting up environment..."
      - python3 --version
      - pip3 --version
      - robot --version
      - export BASE_URL=https://jsonplaceholder.typicode.com

  build:
    commands:
      - echo "Running Robot Framework tests..."
      - mkdir -p output
      - robot -d output mentorShip.robot

  post_build:
    commands:
      - echo "Archiving test results..."
      - mkdir -p artifacts
      - cp output/* artifacts/

artifacts:
  files:
    - artifacts/**
  discard-paths: no
