version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install robotframework
      - pip install robotframework-requests
      - pip install requests
      - pip install robotframework boto3

  pre_build:
    commands:
      - echo "Setting up environment..."
      - python3 --version
      - pip3 --version
      - export BASE_URL=https://jsonplaceholder.typicode.com

  build:
    commands:
      - echo "Running Robot Framework tests..."
      - mkdir -p output
      - robot -d output mentorShip.robot
      - python sendSNS/send_results_sns.py

  post_build:
    commands:
      - echo "Archiving test results..."
      - mkdir -p artifacts
      - cp output/* artifacts/

artifacts:
  files:
    - artifacts/**
  discard-paths: no

env:
  variables:
    OUTPUT_FILE: results/output.xml
    SNS_TOPIC_ARN: arn:aws:sns:us-east-1:535002847900:PipelineSampleNotification
